[package]
name = "triangular-nim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smallvec = "1.13"
rayon = "1.10"

[profile.release]
strip = "debuginfo"
opt-level = 3
lto = "thin"
